name = "trener-poc"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "trener-poc"
database_id = "11c62e4f-8da6-461e-8566-3d1e42c35163"
migrations_dir = "migrations"
